services:
  app:
    image: kooldev/php:8.1-nginx
    ports:
    - ${KOOL_APP_PORT:-80}:80
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
    volumes:
    - .:/app:delegated
    networks:
    - kool_local
    - kool_global
  database:
    image: mysql:5.7
    ports:
    - ${KOOL_DATABASE_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD-rootpass}
      MYSQL_DATABASE: ${DB_DATABASE-database}
      MYSQL_USER: ${DB_USERNAME-user}
      MYSQL_PASSWORD: ${DB_PASSWORD-pass}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
    - database:/var/lib/mysql:delegated
    networks:
    - kool_local
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
volumes:
  database: null
networks:
  kool_local: null
  kool_global:
    external: true
    name: ${KOOL_GLOBAL_NETWORK:-kool_global}
